# 2. NumPy Array Ex
[https://www.w3resource.com/python-exercises/numpy/basic/index.php]

In [1]:
import numpy as np

In [4]:
#1.
print(np.__version__)

1.18.1


In [5]:
#2.
a = [12.23,13.32]
aa = np.array(a)
print(aa)

[12.23 13.32]


In [7]:
# 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
a = np.arange(2,11).reshape(3,-1)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
#4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11
a = np.zeros(10)
a[6] = 11
print(a)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [9]:
# 6. Write a NumPy program to reverse an array (first element becomes last)
a = np.arange(12,38)
ar = a[::-1]
print(a)
print(ar)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [11]:
# 7. Write a NumPy program to convert an array to a float type.
a = np.arange(1,5)
af = np.asfarray(a)
print(af)

[1. 2. 3. 4.]


In [13]:
# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
n = 5
a = np.ones((n,n))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# 9. add a border of 0 around array
a = np.ones((3,3))
a = np.pad(a,pad_width = 1, mode='constant', constant_values = 0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
# 11.
arr = [1,2,3,4]
a = np.asarray(arr)
print(a)
b = ([1,2,3],[2,3,4])
bs = np.array(b)
print(bs)

[1 2 3 4]
[[1 2 3]
 [2 3 4]]


In [27]:
# 12. Write a NumPy program to append values to the end of an array.
a = np.arange(10,31,10)
app = np.arange(40,91,10)
a = np.append(a,app)
print(a)

[10 20 30 40 50 60 70 80 90]


In [29]:
# 13. Write a NumPy program to create an empty and a full array. 
a = np.empty((3,4))
b = np.ones((3,4)) * 5
print(a)
print(b)

[[6.79038654e-313 6.79038653e-313 2.37663529e-312 2.05833592e-312]
 [2.05833592e-312 2.18565567e-312 8.48798317e-313 1.01855798e-312]
 [1.08221785e-312 9.33678148e-313 1.01855798e-312 1.65949350e-076]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [36]:
# 14 Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. 
f = np.array([0,12,45.21,34,99.91])
def f2c(fs):
    return 5*fs/9-5*32/9
c = f2c(f)
print(f)
print(f'{c}')

[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [41]:
# 15. 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers
a = np.array([1+0j,0.7+0.7j])
np.real(a)
np.imag(a)
a.real
a.imag

array([0. , 0.7])

In [43]:
# 16. Write a NumPy program to find the number of elements of an array, 
# length of one array element in bytes and total bytes consumed by the elements.
a = np.array([1,2,3],dtype=np.float64)
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [46]:
# 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array. 
a = np.array([0,10,20,40,60])
b = np.array([0,40])
print(np.in1d(a,b))
print(np.in1d(b,a))

[ True False False  True False]
[ True  True]


In [47]:
# 18. Write a NumPy program to find common values between two arrays. 
a = np.array([0,10,20,40,60])
b = np.array([10,30,40])
print(np.intersect1d(a,b))
print(np.intersect1d(b,a))

[10 40]
[10 40]


In [48]:
# 19. Write a NumPy program to get the unique elements of an array.
a = np.array([10,10,20,20,30,30])
print(np.unique(a))

[10 20 30]


In [50]:
# 20. 
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))
print(np.setdiff1d(array2, array1))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]
[30 50 70]


In [51]:
# 21.
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [52]:
# 22. 
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


In [53]:
# 23. 23. Write a NumPy program to test whether all elements in an array evaluate to True
a = np.array([1,2,3,0])
print(np.all(a))

False


In [54]:
# 23. 23. Write a NumPy program to test whether any elements in an array evaluate to True
a = np.array([1,2,3,0])
print(np.any(a))

True


In [64]:
# 25. repeat array, e.g [1,2] -> [1,2,1,2,]
b = np.array([1,2])
bt = np.tile(b,2)
print(bt)
a = np.array([[0,1],[1,0]])
print(a)
x = np.tile(a,(4,4))
print(x)

[1 2 1 2]
[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [71]:
# 26 Write a NumPy program to repeat elements of an array
a = np.repeat(3,4)
print(a)
b = np.repeat([[1,2,3,4]],2, axis = 0)
print(b)

c = np.repeat([1,2,3,4],2)
print(c)

[3 3 3 3]
[[1 2 3 4]
 [1 2 3 4]]
[1 1 2 2 3 3 4 4]


In [82]:
# 27. 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
a = np.array([1,2,3,4,7,0,5])
a[np.argmax(a)]

b = np.random.randint(1,20,(5,4))
print(b)
print(np.argmax(b,axis = 0))
print(np.argmax(b,axis = 1))
print(np.argmax(b))
#convert to 2d index
ind = np.unravel_index(np.argmax(b,axis=None),b.shape)
print(ind)

[[ 2 14  1 18]
 [12  7  3 19]
 [ 6 12 18  5]
 [17 19  1 17]
 [13 19 19 15]]
[3 3 4 1]
[3 3 2 1 1]
7
(1, 3)


In [88]:
# 29. Write a NumPy program to sort an along the first, last axis of an array. 
a = np.random.randint(0,20,(3,3))
print(np.sort(a,axis=0)) # along colums
print(np.sort(a))
print(np.sort(a,axis=-1)) # along rows


[[ 3  1  6]
 [ 5  4 12]
 [11  5 17]]
[[ 1  5  6]
 [ 3  4 17]
 [ 5 11 12]]
[[ 1  5  6]
 [ 3  4 17]
 [ 5 11 12]]
