# 101 NumPY Exercises for Data Analysis

Link: [https://www.machinelearningplus.com/python/101-numpy-exercises-python/]

In [1]:
import numpy as np

In [2]:
#1 . show version
print(np.__version__)

1.18.1


In [3]:
#2. 1d array
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#3. create a boolean array
# 3x3 all true
a = np.ones((3,3),dtype = bool)
print(a)
#
a = np.full((3,3),True,dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
#4. extract all odd numbers
a = np.arange(0,10)
odd = a[a%2 == 1]
print(odd)

[1 3 5 7 9]


In [9]:
#5 replace all odd numbers with -1 INPLACE
a = np.arange(0,10)
a[a%2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
#6 replace conditional without changing orignal array
a = np.arange(0,10)
out = np.where(a %2==1, -1, a)
print(a)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
#7. reshape array
a = np.arange(10)
am = a.reshape(2,-1)
print(am)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
#8. stack arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a,b,sep='\n\n')

# sol 1
print(np.append(a,b,axis = 0))

# sol 2
print(np.concatenate([a,b],axis=0))

# sol 3
print(np.vstack([a,b]))

#sol 4
print(np.r_[a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
#9. stack horizontally
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

print(np.append(a,b,axis=1))
#or
print(np.hstack([a,b]))
#or
print(np.concatenate([a,b],axis = 1))
# or
print(np.c_[a,b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [32]:
# 10. custom sequences
a = np.array([1,2,3])
p1 = np.repeat(a,3)
p2 = np.tile(a,3)
result = np.append(p1,p2)
print(result)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [33]:
# 11. common items betweens arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.intersect1d(a,b)
print(result)

[2 4]


In [34]:
# 12 remove all items from a alspo present in b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a,b)
print(result)

[1 2 3 4]


In [41]:
# 13. get positions where elemtns match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.where(a==b)
print(result[0].tolist())

[1, 3, 5, 7]


In [44]:
# 14 get all numbers within a range
a = np.array([2,6,1,9,10,3,27])

#1
index = np.where((a>=5) & (a<=10))
a[index]

#2 
index = np.where(np.logical_and(a>=5,a<=10))

#3
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [49]:
# 15. maje function for scalars work on arrays
def myFunc(a,b):
    if a<b:
        return a+b
    else:
        return a-b

a = np.random.randint(1,10,10)
b = np.random.randint(1,10,10)

pair_func = np.vectorize(myFunc,otypes=[int])
pair_func(a,b)


array([11, 10,  5,  3,  0,  2,  4,  4,  3, 13])

In [53]:
#  16. swap columns in array
a = np.arange(1,10).reshape(3,-1)
asw = a[:,[1,0,2]]
print(a)
print(asw)#sep='\t->\t')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [54]:
#17 swap rows
a = np.arange(1,10).reshape(3,-1)
asw = a[[1,0,2],:]
print(asw)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [57]:
# 18 reverse rows
a = np.arange(1,10).reshape(3,-1)
arev = a[::-1]
print(arev)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [58]:
# 19 reverse cols
a = np.arange(1,10).reshape(3,-1)
arev = a[:,::-1]
print(arev)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [59]:
# 20 create random array with floats between 5 and 10
a = np.random.uniform(5,10,size=(5,3))
print(a)

[[5.20715921 5.15838641 5.32989325]
 [5.98940222 9.25080922 6.13292264]
 [6.54270219 9.85034014 8.59595765]
 [5.48943674 7.23071467 9.07976841]
 [8.916648   9.53732255 6.53563344]]


In [60]:
# 21 format output to 3 decimal places in array
a = np.random.random((5,3))
print(a)
np.set_printoptions(precision = 3)
print(a)

[[0.16918787 0.74852371 0.88568763]
 [0.73038573 0.07719329 0.46279756]
 [0.75842396 0.48374036 0.29055641]
 [0.63413465 0.79407531 0.13822294]
 [0.33063126 0.32852324 0.99660863]]
[[0.169 0.749 0.886]
 [0.73  0.077 0.463]
 [0.758 0.484 0.291]
 [0.634 0.794 0.138]
 [0.331 0.329 0.997]]


In [65]:
# 22 suprres scientific notation
#reset
np.set_printoptions(suppress = False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress = True)
print(rand_arr)

[[5.43405e-04 2.78369e-04 4.24518e-04]
 [8.44776e-04 4.71886e-06 1.21569e-04]
 [6.70749e-04 8.25853e-04 1.36707e-04]]
[[0.00054 0.00028 0.00042]
 [0.00084 0.      0.00012]
 [0.00067 0.00083 0.00014]]


In [77]:
# 23 print not all values
a = np.arange(15)
print(a)
np.set_printoptions(threshold = 6)
print(a)
np.set_printoptions(threshold = np.inf) #RESET 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2 ... 12 13 14]


In [79]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [89]:
# 25 import iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object') #object to keep text
iris.shape

(150, 5)

In [84]:
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [86]:
# extract a cilumn from 1d array of tuples
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

C:\Users\sotso\anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [94]:
# extract only the type (text field row 4)
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [97]:
# 27 convert tuples to 2d array
# we have to omit the species text field (array same type)

# SOlution 1
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])

#Solution 2
# only load colums 0-3
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols = [0,1,2,3])


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [100]:
# 28. compute mean, std of sepallength
sepallength = iris_2d[:,0]

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu,med,sd)

5.843333333333334 5.8 0.8253012917851409


In [105]:
# 29. normalize values in sepallength
a = np.min(sepallength)
b = np.max(sepallength)
# sepallength_norm = (sepallength - a)/ (b-a)

# or
sepallength_norm = (sepallength -a) / sepallength.ptp() # ptp is range

print(np.min(sepallength_norm),np.max(sepallength_norm))

0.0 1.0


In [107]:
# 30 . softmax
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

print(softmax(sepallength))

[0.00222 0.00182 0.00149 0.00135 0.00201 0.003   0.00135 0.00201 0.0011
 0.00182 0.003   0.00164 0.00164 0.001   0.00447 0.00404 0.003   0.00222
 0.00404 0.00222 0.003   0.00222 0.00135 0.00222 0.00164 0.00201 0.00201
 0.00245 0.00245 0.00149 0.00164 0.003   0.00245 0.00331 0.00182 0.00201
 0.00331 0.00182 0.0011  0.00222 0.00201 0.00122 0.0011  0.00201 0.00222
 0.00164 0.00222 0.00135 0.00271 0.00201 0.01484 0.00814 0.01343 0.00331
 0.009   0.00404 0.00737 0.00182 0.00995 0.00245 0.00201 0.00494 0.00546
 0.00603 0.00366 0.01099 0.00366 0.00447 0.00667 0.00366 0.00494 0.00603
 0.00737 0.00603 0.00814 0.00995 0.01215 0.01099 0.00546 0.00404 0.00331
 0.00331 0.00447 0.00546 0.003   0.00546 0.01099 0.00737 0.00366 0.00331
 0.00331 0.00603 0.00447 0.00201 0.00366 0.00404 0.00404 0.00667 0.00222
 0.00404 0.00737 0.00447 0.0164  0.00737 0.009   0.02704 0.00182 0.02003
 0.01099 0.01813 0.009   0.00814 0.01215 0.00404 0.00447 0.00814 0.009
 0.02988 0.02988 0.00546 0.01343 0.00366 0.02988 0.007

In [108]:
# 31. percentile scores
np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

In [115]:
# 32 insert values at random position
iris_work = iris_2d.copy()

# sol 1
i,j = np.where(iris_work) # i,j contain r/c of all values
iris_work[np.random.choice((i),20),np.random.choice((j),20)] = np.nan

# sol 2
iris_work = iris_2d.copy()
iris_work[np.random.randint(150,size=20),np.random.randint(4,size=20)] = np.nan

print(iris_work[:20])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 nan]
 [4.9 3.1 1.5 0.1]
 [5.4 nan 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


In [120]:
# 33. Find posiution of missing values in a colums

pos = np.where(np.isnan(iris_work[:,0]))
numofnan = np.isnan(iris_work[:,0]).sum()

In [121]:
numofnan

5

In [123]:
# 34 filter on more conditions
condition = (iris_2d[:,2] > 1.5) & (iris_2d[:,0]< 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [128]:
idd = np.where((iris_2d[:,2]> 1.5) & (iris_2d[:,0]< 5.0))
iris_2d[idd,:]

array([[[4.8, 3.4, 1.6, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [4.9, 2.4, 3.3, 1. ],
        [4.9, 2.5, 4.5, 1.7]]])

In [135]:
# 35. select all rows without nan
iris_work[np.sum(np.isnan(iris_work),axis=1) == 0]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3

In [138]:
np.isnan(iris_work).any()

True

In [145]:
# 41 create a new column from exisiting columns
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = iris_2d[:,0].astype('float')
petallength = iris_2d[:,2].astype('float')
volume = (np.pi*petallength*(sepallength**2)) / 3

# new axis
volume = volume[:,np.newaxis] 
v2 = volume.resh

In [146]:
volume

array([[ 38.13265],
       [ 35.2005 ],
       [ 30.07237],
       [ 33.23805],
       [ 36.65191],
       [ 51.91168],
       [ 31.02218],
       [ 39.26991],
       [ 28.38324],
       [ 37.71482],
       [ 45.80442],
       [ 38.60389],
       [ 33.7784 ],
       [ 21.29895],
       [ 42.27327],
       [ 51.03517],
       [ 39.69716],
       [ 38.13265],
       [ 57.83986],
       [ 40.85641],
       [ 51.91168],
       [ 40.85641],
       [ 22.1587 ],
       [ 46.30393],
       [ 45.84212],
       [ 41.8879 ],
       [ 41.8879 ],
       [ 42.47433],
       [ 39.64271],
       [ 37.01215],
       [ 38.60389],
       [ 45.80442],
       [ 42.47433],
       [ 44.34882],
       [ 37.71482],
       [ 31.41593],
       [ 41.18104],
       [ 37.71482],
       [ 26.35587],
       [ 40.85641],
       [ 34.03392],
       [ 27.56748],
       [ 26.35587],
       [ 41.8879 ],
       [ 51.75146],
       [ 33.7784 ],
       [ 43.58017],
       [ 31.02218],
       [ 44.12367],
       [ 36.65191],
